$ErrorActionPreference = 'Stop'

# Update styles.css
Write-Host 'Updating styles.css...'
$css = Get-Content -Path 'styles.css' -Raw -Encoding UTF8
$css = $css -replace '--bg-root:\s*#0a0e1a;', '--bg-root:          #0D1425;'
$css = $css -replace '--bg-control-panel:\s*#080c16;', '--bg-control-panel: #0D1425;'
$css = $css -replace '--border-focus:\s*rgba\(139, 92, 246, 0.5\);', '--border-focus:     rgba(212, 175, 55, 0.5);'
if ($css -notmatch '.control-panel \{ display: none !important; \}') {
    $css += "`n`n/* Ngabo UI Updates */`n.control-panel { display: none !important; }`n"
}
Set-Content -Path 'styles.css' -Value $css -Encoding UTF8

# Update index.html
Write-Host 'Updating index.html...'
$html = Get-Content -Path 'index.html' -Raw -Encoding UTF8
$html = $html.Replace('KioskControl UG — The mobile money business operating system', 'Ngabo v1.0 — The mobile money business operating system')
$html = $html.Replace('KioskControl UG - The mobile money business operating system', 'Ngabo v1.0 - The mobile money business operating system')
$html = $html.Replace('content="KioskControl"', 'content="Ngabo"')
$html = $html.Replace('KioskControl UG — Business Control System', 'Ngabo — Business Control System')
$html = $html.Replace('KioskControl UG - Business Control System', 'Ngabo - Business Control System')
$html = $html.Replace('KioskControl Simulator', 'Ngabo Simulator')
$html = $html.Replace('KioskControl UG', 'Ngabo')
$html = $html.Replace('KioskControl requests permission', 'Ngabo requests permission')
$html = $html.Replace('grant KioskControl explicit authorization', 'grant Ngabo explicit authorization')
$html = $html.Replace('About KioskControl', 'About Ngabo')
$html = $html.Replace('2.0.0 — Phase 1 MVP', 'Ngabo v1.0')
$html = $html.Replace('2.0.0 - Phase 1 MVP', 'Ngabo v1.0')
$html = $html -replace '(?s)<div class="pricing-tiers">.*?</div>\s*<div class="settings-item">', '<div class="settings-item">'
Set-Content -Path 'index.html' -Value $html -Encoding UTF8

# Update app.js
Write-Host 'Updating app.js...'
$js = Get-Content -Path 'app.js' -Raw -Encoding UTF8
$js = $js.Replace('KioskControl UG - Mobile Money Business Operating System v2.0', 'Ngabo - Capital Control System v1.0')
$js = $js.Replace('KioskControl Main', 'Ngabo Main')
$js = $js.Replace('You must accept to use KioskControl', 'You must accept to use Ngabo')
$js = $js.Replace('*KioskControl Daily Report', '*Ngabo Daily Report')
$js = $js.Replace('Generated by KioskControl UG', 'Generated by Ngabo')
Set-Content -Path 'app.js' -Value $js -Encoding UTF8

Write-Host 'Success!'
